'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Category
    Public Property CategoryID As Integer
    Public Property CategoryName As String
    Public Property Description As String

    Public Overridable Property Products As ICollection(Of Product) = New HashSet(Of Product)

End Class
Partial Public Class CustomerInfo
    Public Property UserId As Integer
    Public Property FirstName As String
    Public Property LastName As String
    Public Property Address As String
    Public Property PostalCode As String
    Public Property PhoneNumber As String
    Public Property Email As String

    Public Overridable Property OrderDetails As ICollection(Of OrderDetail) = New HashSet(Of OrderDetail)

End Class
Partial Public Class OrderDetail
    Public Property OrderID As Integer
    Public Property ProductID As Integer
    Public Property UserId As Integer
    Public Property CategoryID As Integer
    Public Property ProductName As String
    Public Property UnitPrice As Decimal
    Public Property Quantity As Integer

    Public Overridable Property CustomerInfo As CustomerInfo
    Public Overridable Property Product As Product

End Class
Partial Public Class Product
    Public Property ProductID As Integer
    Public Property CategoryID As Nullable(Of Integer)
    Public Property ProductName As String
    Public Property ProductImage As String
    Public Property UnitPrice As Decimal

    Public Overridable Property Category As Category
    Public Overridable Property OrderDetails As ICollection(Of OrderDetail) = New HashSet(Of OrderDetail)

End Class
